@startuml

class Program
{
    - network : INetwork
    - binaryReader : Packager
    - cursor : Cursor
    - scene : Scene

    - ENTRY_PROGRAM_POINT()
    - MainLoop()
}

class Configuration
{
    {static} musicVolumen : float
    {static} sfxVolumen : float
}

class Scene
{
    - nodes : SceneNode[]
    __
    + init()
    + destroy()
    + tick(deltaTime)
    __
    + {static} loadScene(data)
}

class SceneNode
{
    - nodes : ref SceneNode[]
    + name : string
    __
    # virtual init() = 0
    # virtual destroy() = 0
    # virtual tick(deltaTime) = 0
    __
    # getSceneNodes() : SceneNode[]
}

class RoomSceneNode
{
    - name : string
    - background : QuadAspectRatio
    - soundPlayer : Sound
    - music : SoundBuffer
    - sfx : SoundBuffer[]
    - cameras : RoomCamera[]
}

class RoomCamera
{
    + texture : Texture
    + mask : Texture
    + anims : BackgroundAnim[]
    + notes : RoomNote[]
}

class RoomNote
{
    owner : string
    avatar : Image
    content : string
    icon : Texture
    position : Vec2u
}

class BackgroundAnim
{
    texture : Texture
    sprite : Sprite
    rate : float
    coord : Vec2u
}

abstract INetwork
{
    + initialize()
    __ConnectionObservers__
    # onConnected()
    # onDisconnected()
    # onError()
    # onKicked()
    # onLoginStatus(success)
    # onRoomChanged(room)
    __PlayersObservers__
    # onPlayerEnterRoom()
    # onPlayerLeaveRoom()
    # onPlayerEnterCamera()
    # onPlayerLeaveCamera()
    # onPlayersList()
    # onPlayerPosition()
    __ChatObservers__
    # onRoomMessage()
    # onPlayerMessage()
    # onPrivateMessage()
    __RoomObservers__
    # onSpawnItem()
    # onDestroyItem()
    __Sends__
    + changeRoom(room)
    + sendMessage(message)
    + takeItem()
}

class SocketIONetwork
{
    - socketClient : Socket.io
}

class DebugNetwork
{
}


'
' Relations
'-----------------------------------------------------------------------------------------------------------------------
INetwork <|-- SocketIONetwork
INetwork <|-- DebugNetwork
INetwork <|-- NullNetwork


SceneNode <|-- RoomSceneNode
SceneNode <|-- LoginScreen

RoomSceneNode *-- RoomCamera
RoomSceneNode *-- QuadAspectRatio

RoomCamera *-- RoomNote
RoomCamera *-- BackgroundAnim

Scene *-- SceneNode

Program *-- Scene
Program *-- INetwork


@enduml